import esbuild from 'esbuild';
import process from 'process';
import { builtinModules } from 'node:module';
import { copyFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';

// Output the complete plugin (main.js + manifest.json + styles.css) into dist/
// so the folder can be copied/symlinked straight into a vault's plugin folder.
const OUT_DIR = 'dist';
const STATIC_ASSETS = ['manifest.json', 'styles.css'];

const copyStaticAssets = {
	name: 'copy-static-assets',
	setup(build) {
		build.onStart(() => {
			mkdirSync(join(ROOT, OUT_DIR), { recursive: true });
		});
		build.onEnd(() => {
			for (const file of STATIC_ASSETS) {
				try {
					copyFileSync(join(ROOT, file), join(ROOT, OUT_DIR, file));
				} catch (err) {
					console.error(`Failed to copy ${file} to ${OUT_DIR}/`, err);
				}
			}
		});
	},
};

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ['src/main.ts'],
	bundle: true,
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	jsx: 'automatic',
	jsxImportSource: 'preact',
	format: 'cjs',
	target: 'es2021',
	// esbuild defaults to `charset: 'ascii'`, which escapes every non-ASCII
	// character as `\uXXXX` — six bytes where UTF-8 needs two. The Russian
	// locale table alone pays ~29 KB for that (docs/plans/m10-perf.md §6).
	// Obsidian reads main.js as UTF-8.
	charset: 'utf8',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outfile: join(ROOT, OUT_DIR, 'main.js'),
	minify: prod,
	plugins: [copyStaticAssets],
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();
}
